repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
    - id: end-of-file-fixer
    - id: trailing-whitespace
    - id: check-executables-have-shebangs
    - id: check-merge-conflict
    - id: debug-statements
- repo: https://github.com/psf/black
  rev: 20.8b1
  hooks:
    - id: black
      exclude: |
        (?x)(
            migrations/|
            ^\.git/|
            ^cache/|
            ^\.cache/|
            ^\.venv/|
            ^\.local
        )
      language_version: python3
      stages: [commit]
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.7.9
  hooks:
    - id: flake8
      # args: [--max-line-length=79]
- repo: https://github.com/Lucas-C/pre-commit-hooks-bandit.git
  rev: v1.0.5
  hooks:
  - id: python-bandit-vulnerability-check
    # args: [-l, --recursive, -x, tests]
    args: [--recursive, --exclude, "*/tests/*", "*/venv/*", "*/.git/*", "*/__pycache__/*"]
    files: .py$
